### PR TITLE
Add multiband operations

### PR DESCRIPTION
**Pull request by moradology**
We have multiband support, but the edges are pretty sharp and there aren't enough expressions to properly deal with them. This PR is an attempt to clean up some of the fallout from the rather large move to multiband images as first class members of MAML

### CODE REVIEW

**Comment by moradology** [comment]
Maybe of interest @pomadchin

**Comment by pomadchin** [comment]
I'm wondering where is this branch located? I can't find it in your fork.

**Comment by pomadchin** [comment]
Ahhhh it's `moradology/maml-1`

**Comment by moradology** [comment]
WIP until we figure out all the operations for integration in backsplash

**Pull request merged**
