### PR TITLE
Restore and test masking implementation

### PR DESCRIPTION
**Pull request by jisantuc**
Overview
-----

This PR restores the implementation of `Masking -> MaskingNode` and upgrades `sbt-crossproject` not
to use a deprecated version.

~I'm not really sure how to test things.~

### CODE REVIEW

**Comment by moradology** [comment]
Great catch, I'm glad this was an easy fix. I'd say that testing in general could use some love but that the change here is pretty minimal - you could (assuming your schedule permits) manually create an AST that uses masking/some super simple `RasterLit` and check that evaluation of the node `NoDatas` the appropriate pixels

**Comment by moradology** [comment]
The RDD work which is killing travis can be ignored; I've created an issue at https://github.com/geotrellis/maml/issues/73

**Comment by jisantuc** [comment]
I _think_ that's what I did in eb5722c

**Comment by jisantuc** [comment]
It's tough to tell though because I can't compile tests :disappointed:

**Comment by jisantuc** [comment]
I should say, I think that's what I did in eb5722c + e6892ab

**Pull request merged**
